package be.kuleuven.gt.gyrodrive.Struct1;

import android.content.Intent;
import android.os.Bundle;
import android.view.View;
import android.widget.Button;
import android.widget.EditText;

import androidx.activity.EdgeToEdge;
import androidx.appcompat.app.AppCompatActivity;
import androidx.core.graphics.Insets;
import androidx.core.view.ViewCompat;
import androidx.core.view.WindowInsetsCompat;

import be.kuleuven.gt.gyrodrive.R;

public class RegisterActivity extends AppCompatActivity {
    private Button btnExitR;
    private Button btnRegisterR;
    private EditText usernameR;
    private EditText passwordR;
    private EditText nameR;
    private EditText surnameR;
    private EditText emailR;


    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        EdgeToEdge.enable(this);
        setContentView(R.layout.activity_register);
        //autogenerated code to correctly setup activity
        ViewCompat.setOnApplyWindowInsetsListener(findViewById(R.id.main), (v, insets) -> {
            Insets systemBars = insets.getInsets(WindowInsetsCompat.Type.systemBars());
            v.setPadding(systemBars.left, systemBars.top, systemBars.right, systemBars.bottom);
            return insets;


        });
        //assigning objects from GUI to variables
        //btnExitR = (Button) findViewById(R.id.btnExitR);
        btnRegisterR = (Button) findViewById(R.id.btnRegisterR);
        usernameR = (EditText) findViewById(R.id.txtUsernameR);
        passwordR = (EditText) findViewById(R.id.txtPasswordR);
        nameR = (EditText) findViewById(R.id.txtNameR);
        surnameR = (EditText) findViewById(R.id.txtSurnameR);
        emailR = (EditText) findViewById(R.id.txtEmailR);
    }

    public void onBtnRegister_Clicked(View Caller) {
    // create new user from data given from form in GUI
        EditText usernameR = (EditText) findViewById(R.id.txtUsernameR);
        EditText passwordR = (EditText) findViewById(R.id.txtPasswordR);
        EditText nameR = (EditText) findViewById(R.id.txtNameR);
        EditText surnameR = (EditText) findViewById(R.id.txtSurnameR);
        EditText emailR = (EditText) findViewById(R.id.txtEmailR);

        //new instance of user
        //id and dates are not passed, they will be generated by database system
        User newRegistredUser = new User(
                Integer.parseInt("0"),
                usernameR.getText().toString(),
                emailR.getText().toString(),
                nameR.getText().toString(),
                surnameR.getText().toString(),
                "",
                "",
                passwordR.getText().toString()
        );
        Intent intent = new Intent(this, RegisterConfirmationActivity.class);
        intent.putExtra("NewRegisteredUser", newRegistredUser);
        startActivity(intent);
    }


}