package be.kuleuven.gt.gyrodrive.Struct1;

import android.os.Parcel;
import android.os.Parcelable;

import org.json.JSONException;
import org.json.JSONObject;

import java.time.LocalDateTime;
import java.util.Date;
import java.util.HashMap;
import java.util.Map;

public class User implements Parcelable {
    //primary key in database autogenerated
    private int id;

    //will be used for identifying users on login and also leader board
    private String username;

    //filled in registration
    private String email;

    //filled in registration
    private String name;

    //filled in registration
    private String surname;

    //autogenerated
    private String creation_date;

    //autogenerated
    private String last_change_date;

    //used on login page
    private String password;

    public static final Creator<User> CREATOR = new Creator<User>() {
        @Override
        public User createFromParcel(Parcel in) {
            return new User(in);
        }
        @Override
        public User[] newArray(int size) {
            return new User[size];
        }
    };
    public User(int id, String username, String email, String name, String surname,
                String creation_date, String last_change_date, String password) {
        this.id = id;
        this.username = username;
        this.email = email;
        this.name = name;
        this.surname = surname;
        this.creation_date = creation_date; // yyyy-mm-dd hh:mm
        this.last_change_date = last_change_date; // yyyy-mm-dd hh:mm
        this.password = password;
    }
    public User(Parcel in) {
        this(
                in.readInt(),
                in.readString(),
                in.readString(),
                in.readString(),
                in.readString(),
                in.readString(),
                in.readString(),
                in.readString()
        );
    }
    //from json string to our class
    public User(JSONObject o) {
        try {
            id = o.getInt("id");
            username = o.getString("username");
            email = o.getString("email");
            name = o.getString("name");
            surname = o.getString("surname");
            creation_date = o.getString("creation_date");
            last_change_date = o.getString("last_change_date");
            password = o.getString("password");
        } catch (JSONException e) {
            e.printStackTrace();
        }
    }


    @Override
    public int describeContents() {
        return 0;
    }
    @Override
    public void writeToParcel(Parcel parcel, int i) {
        parcel.writeInt(id);
        parcel.writeString(username);
        parcel.writeString(email);
        parcel.writeString(name);
        parcel.writeString(surname);
        parcel.writeString(creation_date);
        parcel.writeString(last_change_date);
        parcel.writeString(password);
    }

    //from our class to Json and then database
    public Map<String, String> getPostParameters() {
        Map<String, String> params = new HashMap<>();
        params.put("id", name);
        params.put("username", username);
        params.put("email", email);
        params.put("name", name);
        params.put("surname", surname);
        params.put("creation_date", String.valueOf(creation_date));
        params.put("last_change_date", String.valueOf(last_change_date));
        params.put("password", password);
        return params;

    }



    public String getUsername() {
        return username;
    }

    public String getPassword() {
        return password;
    }


    public String getName() {
        return name;
    }

    public String getSurname() {
        return surname;
    }
}

